// Code generated by propgen. DO NOT EDIT.

package main

import "time"

func (b *Body) Pos() complex128 {
	return b.pos
}

func (b *Body) SetPos(pos complex128) {
	b.pos = pos
}

func (b *Body) Vec() complex128 {
	return b.vec
}

func (b *Body) SetVec(vec complex128) {
	b.vec = vec
}

func (b *Body) T() time.Time {
	return b.t
}

func (b *Body) SetT(t time.Time) {
	b.t = t
}
